name: quickctl
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  google_fonts: ^5.1.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.5.0
  flutter_riverpod: ^2.3.6
  multicast_dns: ^0.3.2
  freezed_annotation: ^2.2.0
  omni_datetime_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/ctlr_sample.json
