name: quickctl
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  google_fonts: ^2.3.1
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^9.2.0
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # generate: true
  # assets:
  #   - assets/images/marukatte.png
